### ISSUE TITLE
Install kubectl by default?

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-docker/bitrise-base#214]
Should we install the kubectl by default? gcloud already exists by default however the kubectl is missing.

> gcloud components install kubectl

```
+ gcloud components install kubectl
ERROR: (gcloud.components.install) 
You cannot perform this action because the Cloud SDK component manager 
is disabled for this installation. You can run the following command 
to achieve the same result for this installation: 
sudo apt-get install kubectl
```

```
kubectl: command not found
```

**Comment by godrei** [comment]
Hi @bootstraponline ,
thanks for the question!
I created a task for the infra team to discuss this question.

**Comment by bitrise-adam** [comment]
Hi @bootstraponline 

Thank you for raising this! We decided not to pre-install kubectl as it doesn't take a long time to install during the build and you might need a specific version of it instead of the potentially old one in the apt repositories.

For now we suggest you use `sudo apt-get install kubectl` or any other officially supported method (https://kubernetes.io/docs/tasks/tools/install-kubectl/).

For these reasons I'm closing this issue.

**Comment by bootstraponline** [comment]
Thanks!
